# AUTOMAÇÃO DE SISTEMAS E PROCESSOS COM PYTHON

### SITUAÇÃO PROBLEMA:

- Todos os dias, o nosso sistema atualiza as vendas do dia anterior.
- Um Analista de Vendas desempenha um trabalho diário de ingerir, analisar, construir um relatório padrão e enviar um e-mail para a diretoria no início do expediente.
- **E-mail da diretoria:** _geoai@gmail.com_
- Simulação de repositório de armazenamento de informações do sistema de vendas: _https://drive.google.com/drive/folders/149xknr9JvrlEnhNWO49zPcw0PW5icxga_

### PROPOSTA DE SOLUÇÃO:
- Para essa situação problema, utilizaremos a biblioteca pyautogui que disponibiliza métodos/funções que automatizam comandos do mouse e do teclado.

### ETAPA DE PLANEJAMENTO & DESIGN THINKING

### ROTEIRO DO PROJETO
- ROTEIRO DO PROJETO 1
  - PASSO 1: Entrar no Sistema (link do drive)
  - PASSO 2: Navegar no sistema para encontrar a base de dados
  - PASSO 3: Exportar a base de dados (download)
  - PASSO 4: Ingerir, tratar e analisar os dados, gerando um relatório estatístico descritivo
  - PASSO 5: Enviar o relatório como arquivo .pdf por email

### CRÉDITOS
- Este é um exercício baseado no curso _Python Impressionador da Hashtag Treinamentos_

## CHEET SHEAT DO PROJETO

##### Guia Rápido de Referência: PyAutoGUI

| Categoria | Comando | O que faz? | Dica de Erro Comum (Bug Alert ⚠️) |
| :--- | :--- | :--- | :--- |
| **Configuração** | `pyautogui.PAUSE` | Define pausa entre comandos. | **Esquecer de configurar:** Sem isso, o robô tenta "atropelar" o Windows e nada funciona. |
| **Mouse** | `pyautogui.click()` | Clica na tela. | **Mudança de resolução:** Se você mudar de monitor, as coordenadas (X, Y) mudam e o robô clica no lugar errado. |
| **Mouse** | `pyautogui.doubleClick()` | Clique duplo. | **Velocidade:** Às vezes o Windows não entende o duplo clique se o PC estiver lento; adicione um `time.sleep` antes. |
| **Mouse** | `pyautogui.rightClick()` | Botão direito. | **Menu contextual:** O menu pode demorar a abrir. Não dê o próximo comando imediatamente. |
| **Mouse** | `pyautogui.moveTo()` | Move o cursor. | **Caminho obstruído:** Tentar mover o mouse enquanto o usuário também está mexendo gera conflito. |
| **Teclado** | `pyautogui.write()` | Digita texto. | **Teclado ABNT2/Estrangeiro:** Caracteres especiais (ç, ~, á) podem sair errados se o layout do teclado for diferente. |
| **Teclado** | `pyautogui.press()` | Aperta uma tecla. | **Nome da tecla:** Escrever `press("ENTER")` em maiúsculo pode dar erro em algumas versões. Use sempre minúsculo: `"enter"`. |
| **Teclado** | `pyautogui.hotkey()` | Atalhos (Ctrl+C). | **Ordem das teclas:** Se colocar `("c", "ctrl")` em vez de `("ctrl", "c")`, o atalho pode não funcionar. |
| **Teclado** | `pyautogui.keyDown()` | Segura uma tecla. | **Esquecer de soltar:** Se você usar `keyDown` e não usar o `keyUp` depois, seu teclado vai ficar "travado" naquela tecla. |

---

##### **Dicas**

- **Segurança (Fail-Safe):** Se o seu robô ficar "maluco", leve o mouse rapidamente para o **canto superior esquerdo da tela**. Isso forçará o programa a parar imediatamente.
- **Atenção ao Tempo:** Sempre use `time.sleep()` ou o `pyautogui.PAUSE`. O computador é muito mais rápido que o carregamento dos sites; sem pausas, o robô tentará clicar em botões que ainda não apareceram.
- **Coordenadas:** Lembre-se que a coordenada `(0,0)` é o topo esquerdo da sua tela.
- Se o comando `pyautogui.write()` não estiver funcionando bem com acentos ou cedilha, a melhor prática profissional é:
    - Copiar o texto para a área de transferência (usando a biblioteca `pyperclip`).
    - Usar o `pyautogui.hotkey('ctrl', 'v')` para colar.

## ETAPA ESPECIAL - Descobrir posição de click de mouse

- Use o código abaixo para descobrir qual a posição de um item que queira clicar

##### CUIDADO: 
- A posição na sua tela é diferente da posição na minha tela
- Utilize sempre a mesma tela para que a automatização funcione
- Trocar de telas pode "quebrar" a automação

In [21]:
# time.sleep(5) ##### Aguardar 5 segundos após o enter
# print(pyautogui.position())

# INÍCIO DO SCRIPT DO PROJETO

In [22]:
#--------------------------------#
# ETAPA 1 - ENTRANDO NO SISTEMA
#--------------------------------#

import pyautogui
import time

# Tempo padrão entre todos os comandos do pyautogui
pyautogui.PAUSE = 1

# Pressionar a tecla do Windows
pyautogui.press('win')

# Digitar Edge
pyautogui.write('edge')

# Apertar enter para abrir o Edge
pyautogui.press('enter')
time.sleep(3) ##### Aguardar 3 segundos após o enter

# definição de endereço em uma variável link
link = "https://drive.google.com/drive/folders/149xknr9JvrlEnhNWO49zPcw0PW5icxga"

# Digitar o site e apertar enter
pyautogui.write(link)
pyautogui.press('enter')
time.sleep(5) ##### Aguardar 5 segundos após o enter

In [23]:
#-------------------------------#
# ETAPA 2 - NAVEGANDO NO SISTEMA
#-------------------------------#

# Duplo click na pasta do drive
pyautogui.click(x=356, y=385, clicks=2)
time.sleep(2) ##### Aguardar 2 segundos após o enter

In [24]:
#-------------------------------#
# ETAPA 3 - DOWNLOAD DA PLANILHA
#-------------------------------#

# OPÇÃO 1 - Clicar em 3 pontos para abrir a lista de ações
pyautogui.click(x=925, y=382)
time.sleep(5) ##### Aguardar 2 segundos após o enter

# OPÇÃO 1 - Clicar em transferir/download
pyautogui.click(x=967, y=347)
time.sleep(15) # Aguardar 2 segundos após o enter

'''
A OPÇÃO 2 tem o seguinte problema, se você não clicar exatamente no mesmo lugar, haverá deslocamento da caixa de ações

##### OPÇÃO 2 - Clicar com botão direito no arquivo
pyautogui.click(x=925, y=382, button='right')
time.sleep(5) ##### Aguardar 2 segundos após o enter

##### OPÇÃO 2 - Clicar em transferir/download
pyautogui.click(x=505, y=346)
time.sleep(15) ##### Aguardar 2 segundos após o enter
'''

"\nA OPÇÃO 2 tem o seguinte problema, se você não clicar exatamente no mesmo lugar, haverá deslocamento da caixa de ações\n\n##### OPÇÃO 2 - Clicar com botão direito no arquivo\npyautogui.click(x=925, y=382, button='right')\ntime.sleep(5) ##### Aguardar 2 segundos após o enter\n\n##### OPÇÃO 2 - Clicar em transferir/download\npyautogui.click(x=505, y=346)\ntime.sleep(15) ##### Aguardar 2 segundos após o enter\n"

In [25]:
#-------------------------------#
# ETAPA 4 - INGESTÃO
#-------------------------------#

import pandas as pd
import os

caminho = r"C:\Users\HP\Downloads\Vendas - Dez.xlsx"

# Importar dados
ds_1 = pd.read_excel(caminho)

# Deletar o arquivo após a importação
if os.path.exists(caminho):
    os.remove(caminho)
    print("Arquivo deletado com sucesso!")
else:
    print("O arquivo não foi encontrado.")

# Exibir o dataframe
ds_1

Arquivo deletado com sucesso!

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final
0,65014,2019-12-01,Shopping Morumbi,Sunga Listrado,5,114,570
1,65014,2019-12-01,Shopping Morumbi,Casaco Listrado,1,269,269
2,65016,2019-12-01,Iguatemi Campinas,Sapato Listrado,2,363,726
3,65016,2019-12-01,Iguatemi Campinas,Casaco,1,250,250
4,65017,2019-12-01,Shopping SP Market,Gorro Liso,3,92,276
...,...,...,...,...,...,...,...
7084,69996,2019-12-26,Center Shopping Uberlândia,Short Listrado,2,102,204
7085,69996,2019-12-26,Center Shopping Uberlândia,Mochila,4,270,1080
7086,69996,2019-12-26,Center Shopping Uberlândia,Pulseira Estampa,1,87,87
7087,69997,2019-12-26,Ribeirão Shopping,Camisa Listrado,1,108,108
7088,69997,2019-12-26,Ribeirão Shopping,Short Linho,2,133,266

In [26]:
#-------------------------------#
# ETAPA 5 - AVALIAÇÃO PRELIMINAR DO DATAFRAME
#-------------------------------#
print('#----------------------------------------------------#')
print('LINHAS & COLUNAS')
print('#----------------------------------------------------#')
print(ds_1.shape)

print('#----------------------------------------------------------#')
print('AVALIAÇÃO PRELIMINAR - ESTATÍSTICA DESCRITIVA AUTOMATIZADA')
print('#----------------------------------------------------------#')
display(ds_1.describe())

#----------------------------------------------------#
LINHAS & COLUNAS
#----------------------------------------------------#
(7089, 7)
#----------------------------------------------------------#
AVALIAÇÃO PRELIMINAR - ESTATÍSTICA DESCRITIVA AUTOMATIZADA
#----------------------------------------------------------#

,Código Venda,Data,Quantidade,Valor Unitário,Valor Final
count,7089.000000,7089,7089.000000,7089.000000,7089.000000
mean,67492.398928,2019-12-13 01:45:49.894202,2.147976,193.651150,411.526449
min,65014.000000,2019-12-01 00:00:00,1.000000,30.000000,30.000000
25%,66211.000000,2019-12-07 00:00:00,1.000000,100.000000,160.000000
50%,67474.000000,2019-12-13 00:00:00,2.000000,150.000000,269.000000
75%,68764.000000,2019-12-19 00:00:00,3.000000,248.000000,524.000000
max,69997.000000,2019-12-26 00:00:00,5.000000,750.000000,3750.000000
std,1450.709530,NaN,1.244048,148.023448,424.007114

In [27]:
#-------------------------------#
# ETAPA 6 - ANÁLISE DE DADOS (ESTATÍSTICA DESCRITIVA)
#-------------------------------#

#--------------------------------------------------------------------#
# VALOR TOTAL DE VENDAS
#--------------------------------------------------------------------#
valor_total_vendido = ds_1['Valor Final'].sum()

#--------------------------------------------------------------------#
# AGRUPAMENTO DE 'Produto' POR  'Código Venda' PARA SABER A 'Quantidade' DE ITENS POR VENDA 
#--------------------------------------------------------------------#
vendas_por_codigo = ds_1.groupby('Código Venda')['Quantidade'].sum()

#--------------------------------------------------------------------#
# VENDA COM MAIOR QUANTIDADE DE 'Produto"
#--------------------------------------------------------------------#
maior_quantidade = vendas_por_codigo.max()

#--------------------------------------------------------------------#
# VENDAS ('Código Venda') COM MAIOR QUANTIDADE DE ITENS ('Produto')
# SELEÇÃO DAS VENDAS ('vendas_por_codigo') COM MAIOR QUANTIDADE ('maior_quantidade')
#--------------------------------------------------------------------#
vendas_maximas = vendas_por_codigo[vendas_por_codigo == maior_quantidade].index

#--------------------------------------------------------------------#
# LISTAR CÓDIGOS DAS MAIORES VENDAS EM UMA STRING SEPARADA POR VÍRGULAS
#--------------------------------------------------------------------#
lista_codigos_vendas_maximas = ','.join(map(str,vendas_maximas))

#--------------------------------------------------------------------#
# VENDA COM MENOR QUANTIDADE DE 'Produto"
#--------------------------------------------------------------------#
menor_quantidade = vendas_por_codigo.min()

#--------------------------------------------------------------------#
# VENDAS ('Código Venda') COM MENOR QUANTIDADE DE ITENS ('Produto')
# SELEÇÃO DAS VENDAS ('vendas_por_codigo') COM MENOR QUANTIDADE ('maior_quantidade')
#--------------------------------------------------------------------#
vendas_minimas = vendas_por_codigo[vendas_por_codigo == menor_quantidade].index

#--------------------------------------------------------------------#
# LISTAR CÓDIGOS DAS MENORES VENDAS EM UMA STRING SEPARADA POR VÍRGULAS
#--------------------------------------------------------------------#
lista_codigos_vendas_minimas = ", ".join(map(str, vendas_minimas))

#--------------------------------------------------------------------#
# VENDAS DE MAIOR VALOR
#--------------------------------------------------------------------#
# AGRUPAR POR 'Código Venda' E SOMAR O 'valor' DE CADA VENDA
valor_por_venda = ds_1.groupby('Código Venda')['Valor Final'].sum()
# ENCONTRAR O VALOR MÁXIMO DESSA SOMA
maior_valor = valor_por_venda.max()
# SELEÇÃO DAS VENDAS COM MAIOR VALOR
codigos_vendas_mais_caras = valor_por_venda[valor_por_venda == maior_valor].index
# LISTAR CÓDIGOS DAS VENDAS DE MAIOR VALOR EM UMA STRING SEPARADA POR VÍRGULAS
lista_codigos_vendas_mais_caras = ','.join(map(str,codigos_vendas_mais_caras))

#--------------------------------------------------------------------#
# VENDAS DE MENOR VALOR
#--------------------------------------------------------------------#
# ENCONTRAR O VALOR MÍNIMO DESSA SOMA
menor_valor = valor_por_venda.min()
# SELEÇÃO DAS VENDAS COM MENOR VALOR
codigos_vendas_mais_baratas = valor_por_venda[valor_por_venda == menor_valor].index
# LISTAR CÓDIGOS DAS VENDAS DE MENOR VALOR EM UMA STRING SEPARADA POR VÍRGULAS
lista_codigos_vendas_mais_baratas = ','.join(map(str,codigos_vendas_mais_baratas))

#--------------------------------------------------------------------#
# MÉDIA DOS VALORES DAS VENDAS
#--------------------------------------------------------------------#
media_vendas = valor_por_venda.mean().round(2)

#--------------------------------------------------------------------#
# MODA DOS VALORES DAS VENDAS
#--------------------------------------------------------------------#
moda_vendas = valor_por_venda.mode().round(2)

#--------------------------------------------------------------------#
# MEDIANA DOS VALORES DAS VENDAS
#--------------------------------------------------------------------#
mediana_vendas = valor_por_venda.median().round(2)

#--------------------------------------------------------------------#
# DESVIO PADRÃO DOS VALORES DAS VENDAS
#--------------------------------------------------------------------#
desvio_padrao_vendas = valor_por_venda.std()


print(f'O valor total das vendas foi R$ {valor_total_vendido:,.2f}')
print(f'A quantidade de vendas foi: {ds_1['Código Venda'].nunique()}') # Quantidade de vendas
print(f"A maior quantidade de produtos em uma venda foi: {maior_quantidade}")
print(f"O código da venda correspondente é: {lista_codigos_vendas_maximas}")
print(f'A venda de maior valor foi R$ {lista_codigos_vendas_mais_caras}')
print(f"A menor quantidade de produtos foi: {menor_quantidade}")
print(f"Os códigos das vendas correspondentes são: {lista_codigos_vendas_minimas}")
print(f'A venda de menor valor foi: {lista_codigos_vendas_mais_baratas}')
print(f'O maior valor em vendas foi de R$ {maior_valor:,.2f}')
print(f'O menor valor em vendas foi de R$ {menor_valor:,.2f}')
print(f'A média dos valores das vendas (Ticket médio) foi de R$ {media_vendas:,.2f}')
print(f'A moda dos valores das vendas foi de R$ {moda_vendas[0]:,.2f}')
print(f'A mediana dos valores das vendas foi de R$ {mediana_vendas:,.2f}')
print(f"O desvio padrão das vendas foi de: R$ {desvio_padrao_vendas:,.2f}")

O valor total das vendas foi R$ 2,917,311.00
A quantidade de vendas foi: 3787
A maior quantidade de produtos em uma venda foi: 20
O código da venda correspondente é: 65793
A venda de maior valor foi R$ 65793
A menor quantidade de produtos foi: 1
Os códigos das vendas correspondentes são: 65027, 65033, 65036, 65051, 65068, 65077, 65088, 65095, 65111, 65112, 65128, 65142, 65144, 65150, 65165, 65167, 65180, 65181, 65182, 65186, 65205, 65209, 65211, 65225, 65230, 65237, 65243, 65251, 65254, 65267, 65274, 65278, 65282, 65322, 65324, 65325, 65330, 65334, 65341, 65355, 65363, 65386, 65387, 65389, 65410, 65423, 65432, 65438, 65440, 65442, 65461, 65462, 65464, 65479, 65482, 65484, 65491, 65493, 65494, 65507, 65508, 65519, 65533, 65534, 65536, 65539, 65554, 65556, 65559, 65561, 65562, 65565, 65573, 65577, 65584, 65588, 65597, 65605, 65620, 65642, 65645, 65646, 65650, 65652, 65664, 65667, 65668, 65670, 65683, 65694, 65705, 65718, 65728, 65736, 65751, 65761, 65763, 65773, 65777, 65778, 65800, 65802, 65814, 65823, 65835, 65843, 65852, 65860, 65863, 65867, 65868, 65872, 65874, 65879, 65885, 65888, 65900, 65901, 65916, 65920, 65941, 65976, 65979, 65987, 65990, 65999, 66005, 66009, 66016, 66017, 66018, 66020, 66023, 66028, 66030, 66043, 66056, 66074, 66075, 66087, 66100, 66101, 66112, 66115, 66124, 66132, 66133, 66140, 66148, 66152, 66155, 66169, 66170, 66175, 66179, 66182, 66188, 66191, 66194, 66203, 66205, 66206, 66207, 66209, 66212, 66217, 66218, 66230, 66231, 66250, 66266, 66268, 66270, 66276, 66281, 66282, 66283, 66285, 66286, 66290, 66291, 66307, 66315, 66321, 66330, 66337, 66338, 66346, 66347, 66350, 66359, 66372, 66378, 66388, 66391, 66403, 66408, 66411, 66412, 66415, 66422, 66443, 66444, 66458, 66466, 66474, 66482, 66483, 66487, 66488, 66491, 66521, 66531, 66532, 66542, 66545, 66550, 66564, 66566, 66574, 66580, 66581, 66589, 66596, 66608, 66619, 66625, 66626, 66631, 66635, 66642, 66644, 66645, 66651, 66668, 66676, 66700, 66704, 66712, 66714, 66726, 66732, 66739, 66744, 66750, 66751, 66765, 66770, 66771, 66773, 66783, 66785, 66791, 66798, 66800, 66801, 66807, 66808, 66819, 66822, 66823, 66826, 66852, 66866, 66867, 66873, 66874, 66883, 66890, 66910, 66913, 66915, 66923, 66948, 66950, 66985, 66987, 66988, 66992, 67000, 67010, 67011, 67013, 67014, 67022, 67031, 67053, 67056, 67065, 67069, 67072, 67081, 67104, 67107, 67109, 67110, 67114, 67118, 67121, 67125, 67141, 67148, 67154, 67163, 67168, 67191, 67204, 67206, 67207, 67208, 67210, 67217, 67222, 67224, 67235, 67251, 67253, 67265, 67271, 67274, 67276, 67282, 67283, 67298, 67307, 67339, 67341, 67342, 67348, 67358, 67384, 67391, 67395, 67396, 67412, 67414, 67417, 67427, 67428, 67435, 67448, 67449, 67456, 67464, 67478, 67480, 67487, 67490, 67505, 67509, 67511, 67517, 67526, 67530, 67543, 67550, 67557, 67573, 67574, 67580, 67590, 67596, 67619, 67622, 67624, 67629, 67633, 67638, 67643, 67645, 67655, 67657, 67660, 67671, 67678, 67692, 67696, 67697, 67702, 67713, 67716, 67717, 67719, 67728, 67730, 67744, 67784, 67791, 67795, 67806, 67808, 67809, 67819, 67831, 67832, 67835, 67862, 67863, 67868, 67872, 67873, 67875, 67880, 67895, 67901, 67908, 67909, 67910, 67917, 67922, 67930, 67933, 67934, 67939, 67945, 67949, 67957, 67963, 67980, 67983, 67988, 67995, 67996, 68008, 68009, 68012, 68024, 68031, 68037, 68047, 68051, 68065, 68066, 68070, 68092, 68101, 68102, 68111, 68116, 68143, 68145, 68160, 68162, 68168, 68171, 68175, 68177, 68193, 68194, 68198, 68199, 68210, 68212, 68217, 68224, 68229, 68237, 68242, 68247, 68250, 68255, 68262, 68274, 68280, 68281, 68288, 68290, 68302, 68306, 68312, 68314, 68326, 68327, 68329, 68331, 68335, 68337, 68338, 68344, 68359, 68361, 68369, 68371, 68376, 68380, 68381, 68382, 68386, 68388, 68403, 68407, 68421, 68433, 68451, 68458, 68464, 68465, 68469, 68474, 68479, 68503, 68507, 68514, 68518, 68525, 68529, 68536, 68541, 68545, 68550, 68553, 68574, 68581, 68588, 68599, 68601, 68606, 68621, 68629, 68634, 68638, 68639, 68657, 68660, 68661, 68671, 68679, 68690, 68692, 68693, 68695, 68704, 68705, 68720, 68730, 68737, 68739, 68750, 68752, 68755, 68760, 68783, 68785, 68787, 68788, 68790, 68791, 68795, 68802, 68803, 68806, 68807, 68811, 68832, 68843, 68848, 68856, 68859, 68864, 68870, 68872, 68880, 68887, 68892, 68896, 68898, 68900, 68906, 68920, 68924, 68937, 68948, 68956, 68957, 68960, 68961, 68963, 68972, 68979, 68999, 69027, 69045, 69048, 69060, 69063, 69065, 69073, 69097, 69101, 69105, 69111, 69142, 69161, 69164, 69166, 69198, 69202, 69208, 69210, 69215, 69221, 69224, 69240, 69243, 69246, 69251, 69253, 69262, 69271, 69275, 69282, 69290, 69309, 69315, 69318, 69319, 69324, 69332, 69335, 69351, 69354, 69360, 69362, 69373, 69403, 69427, 69432, 69434, 69435, 69438, 69441, 69463, 69464, 69467, 69488, 69500, 69504, 69505, 69518, 69523, 69524, 69529, 69535, 69537, 69549, 69553, 69554, 69561, 69564, 69567, 69581, 69582, 69586, 69597, 69600, 69608, 69609, 69610, 69611, 69637, 69641, 69645, 69654, 69655, 69672, 69675, 69679, 69681, 69685, 69686, 69691, 69695, 69703, 69713, 69720, 69734, 69735, 69738, 69753, 69756, 69757, 69760, 69770, 69790, 69791, 69792, 69822, 69825, 69831, 69835, 69836, 69837, 69848, 69858, 69865, 69867, 69871, 69888, 69891, 69928, 69936, 69943, 69950, 69956, 69957, 69965, 69977, 69980, 69993, 69994
A venda de menor valor foi: 68371,69597,69928
O maior valor em vendas foi de R$ 6,397.00
O menor valor em vendas foi de R$ 30.00
A média dos valores das vendas (Ticket médio) foi de R$ 770.35
A moda dos valores das vendas foi de R$ 200.00
A mediana dos valores das vendas foi de R$ 550.00
O desvio padrão das vendas foi de: R$ 716.09

In [28]:
#----------------------------------------------#
# ETAPA 7 - ELABORAÇÃO DE GRÁFICOS & DIAGRAMAS
#----------------------------------------------#

import plotly.express as px

# Criar um Histograma com Boxplot na margem
fig = px.histogram(
    ds_1, 
    x="Valor Final", 
    nbins=50, # Quantidade de barras (ajustar se necessário)
    title="Análise de Assimetria e Distribuição de Vendas",
    marginal="box", # Adiciona o Boxplot logo acima do histograma!
    color_discrete_sequence=['#636EFA'] # Cor azul profissional
)

# Estilização do gráfico
fig.update_layout(
    xaxis_title="Valor da Venda (R$)",
    yaxis_title="Frequência (Quantidade de Vendas)",
    bargap=0.1 # Espaço entre as barras
)

fig.show()

In [29]:
#----------------------------------------------#
# ETAPA 8 - CRIAÇÃO DE RELATÓRIO DINÂMICO
#----------------------------------------------#

from IPython.display import display, Markdown

# CRIAR RELATÓRIO COM CONTEÚDO DINÂMICO

relatorio = f"""
# Relatório de Análise Estatística de Vendas

## 1. Visão Geral da Operação
O conjunto de dados analisado apresenta o desempenho de vendas do período, focado no volume transacional e faturamento por nota fiscal (Código Venda).

*   **Volume Total de Vendas (Únicas):** {ds_1['Código Venda'].nunique()} transações.
*   **Ticket Médio (Média por Venda):** R$ {media_vendas:,.2f}
*   **Mediana das Vendas:** R$ {mediana_vendas:,.2f}

## 2. Tendência Central e Dispersão
A análise das medidas de tendência central revela uma **Assimetria Positiva (à Direita)** no faturamento.

*   **Moda:** R$ {moda_vendas[0]:,.2f}
*   **Desvio Padrão:** R$ {desvio_padrao_vendas:,.2f}
*   **Comportamento da Distribuição:** O fato da Média (R$ {media_vendas:,.2f}) ser superior à Mediana (R$ {mediana_vendas:,.2f}) confirma que o faturamento é impulsionado por um grupo seleto de vendas de alto valor, enquanto a maioria das transações se concentra em patamares menores.

## 3. Análise do Boxplot (Distribuição de Frequência)
A leitura visual do diagrama de caixa e do histograma permite identificar:

*   **Primeiro Quartil (Q1):** R$ 262.00 (25% das vendas estão abaixo deste valor).
*   **Terceiro Quartil (Q3):** R$ 1,042.50 (75% das vendas estão abaixo deste valor).
*   **Intervalo Interquartil:** A concentração de 50% das vendas ocorre em uma faixa estreita, indicando uma padronização no consumo da maioria dos clientes.
*   **Outliers:** Identificamos vendas excepcionais fora das hastes (whiskers), que representam oportunidades de grandes contas ou compras fora do padrão usual de consumo.

## 4. Extremos e Recordes
Identificação das transações que mais se destacaram no período:

## Volume de Itens
*   **Maior Quantidade de Itens:** {maior_quantidade} unidades (Vendas: {lista_codigos_vendas_maximas}).
*   **Menor Quantidade de Itens:** {menor_quantidade} unidade (Vendas: {lista_codigos_vendas_minimas}).

## Valores Financeiros
*   **Venda de Maior Faturamento:** R$ {maior_valor:,.2f} (Código: {lista_codigos_vendas_mais_caras}).
*   **Venda de Menor Faturamento:** R$ {menor_valor:,.2f} (Código: {lista_codigos_vendas_mais_baratas}).

---

## 5. Conclusões e Insights
1.  **Perfil de Venda:** A operação é caracterizada por um alto volume de vendas de ticket baixo/médio, com a presença de "vendas estrela" que elevam a média geral.
2.  **Consistência:** O desvio padrão de R$ {desvio_padrao_vendas:,.2f} sugere uma variação considerável, recomendando-se uma análise mais profunda sobre os produtos que compõem as vendas *outliers* para tentar replicar esse comportamento em outros clientes.

---

"""

# EXIBIR RELATÓRIO FORMATADO
display(Markdown(relatorio))

# Relatório de Análise Estatística de Vendas

## 1. Visão Geral da Operação
O conjunto de dados analisado apresenta o desempenho de vendas do período, focado no volume transacional e faturamento por nota fiscal (Código Venda).

*   **Volume Total de Vendas (Únicas):** 3787 transações.
*   **Ticket Médio (Média por Venda):** R$ 770.35
*   **Mediana das Vendas:** R$ 550.00

## 2. Tendência Central e Dispersão
A análise das medidas de tendência central revela uma **Assimetria Positiva (à Direita)** no faturamento.

*   **Moda:** R$ 200.00
*   **Desvio Padrão:** R$ 716.09
*   **Comportamento da Distribuição:** O fato da Média (R$ 770.35) ser superior à Mediana (R$ 550.00) confirma que o faturamento é impulsionado por um grupo seleto de vendas de alto valor, enquanto a maioria das transações se concentra em patamares menores.

## 3. Análise do Boxplot (Distribuição de Frequência)
A leitura visual do diagrama de caixa e do histograma permite identificar:

*   **Primeiro Quartil (Q1):** R$ 262.00 (25% das vendas estão abaixo deste valor).
*   **Terceiro Quartil (Q3):** R$ 1,042.50 (75% das vendas estão abaixo deste valor).
*   **Intervalo Interquartil:** A concentração de 50% das vendas ocorre em uma faixa estreita, indicando uma padronização no consumo da maioria dos clientes.
*   **Outliers:** Identificamos vendas excepcionais fora das hastes (whiskers), que representam oportunidades de grandes contas ou compras fora do padrão usual de consumo.

## 4. Extremos e Recordes
Identificação das transações que mais se destacaram no período:

## Volume de Itens
*   **Maior Quantidade de Itens:** 20 unidades (Vendas: 65793).
*   **Menor Quantidade de Itens:** 1 unidade (Vendas: 65027, 65033, 65036, 65051, 65068, 65077, 65088, 65095, 65111, 65112, 65128, 65142, 65144, 65150, 65165, 65167, 65180, 65181, 65182, 65186, 65205, 65209, 65211, 65225, 65230, 65237, 65243, 65251, 65254, 65267, 65274, 65278, 65282, 65322, 65324, 65325, 65330, 65334, 65341, 65355, 65363, 65386, 65387, 65389, 65410, 65423, 65432, 65438, 65440, 65442, 65461, 65462, 65464, 65479, 65482, 65484, 65491, 65493, 65494, 65507, 65508, 65519, 65533, 65534, 65536, 65539, 65554, 65556, 65559, 65561, 65562, 65565, 65573, 65577, 65584, 65588, 65597, 65605, 65620, 65642, 65645, 65646, 65650, 65652, 65664, 65667, 65668, 65670, 65683, 65694, 65705, 65718, 65728, 65736, 65751, 65761, 65763, 65773, 65777, 65778, 65800, 65802, 65814, 65823, 65835, 65843, 65852, 65860, 65863, 65867, 65868, 65872, 65874, 65879, 65885, 65888, 65900, 65901, 65916, 65920, 65941, 65976, 65979, 65987, 65990, 65999, 66005, 66009, 66016, 66017, 66018, 66020, 66023, 66028, 66030, 66043, 66056, 66074, 66075, 66087, 66100, 66101, 66112, 66115, 66124, 66132, 66133, 66140, 66148, 66152, 66155, 66169, 66170, 66175, 66179, 66182, 66188, 66191, 66194, 66203, 66205, 66206, 66207, 66209, 66212, 66217, 66218, 66230, 66231, 66250, 66266, 66268, 66270, 66276, 66281, 66282, 66283, 66285, 66286, 66290, 66291, 66307, 66315, 66321, 66330, 66337, 66338, 66346, 66347, 66350, 66359, 66372, 66378, 66388, 66391, 66403, 66408, 66411, 66412, 66415, 66422, 66443, 66444, 66458, 66466, 66474, 66482, 66483, 66487, 66488, 66491, 66521, 66531, 66532, 66542, 66545, 66550, 66564, 66566, 66574, 66580, 66581, 66589, 66596, 66608, 66619, 66625, 66626, 66631, 66635, 66642, 66644, 66645, 66651, 66668, 66676, 66700, 66704, 66712, 66714, 66726, 66732, 66739, 66744, 66750, 66751, 66765, 66770, 66771, 66773, 66783, 66785, 66791, 66798, 66800, 66801, 66807, 66808, 66819, 66822, 66823, 66826, 66852, 66866, 66867, 66873, 66874, 66883, 66890, 66910, 66913, 66915, 66923, 66948, 66950, 66985, 66987, 66988, 66992, 67000, 67010, 67011, 67013, 67014, 67022, 67031, 67053, 67056, 67065, 67069, 67072, 67081, 67104, 67107, 67109, 67110, 67114, 67118, 67121, 67125, 67141, 67148, 67154, 67163, 67168, 67191, 67204, 67206, 67207, 67208, 67210, 67217, 67222, 67224, 67235, 67251, 67253, 67265, 67271, 67274, 67276, 67282, 67283, 67298, 67307, 67339, 67341, 67342, 67348, 67358, 67384, 67391, 67395, 67396, 67412, 67414, 67417, 67427, 67428, 67435, 67448, 67449, 67456, 67464, 67478, 67480, 67487, 67490, 67505, 67509, 67511, 67517, 67526, 67530, 67543, 67550, 67557, 67573, 67574, 67580, 67590, 67596, 67619, 67622, 67624, 67629, 67633, 67638, 67643, 67645, 67655, 67657, 67660, 67671, 67678, 67692, 67696, 67697, 67702, 67713, 67716, 67717, 67719, 67728, 67730, 67744, 67784, 67791, 67795, 67806, 67808, 67809, 67819, 67831, 67832, 67835, 67862, 67863, 67868, 67872, 67873, 67875, 67880, 67895, 67901, 67908, 67909, 67910, 67917, 67922, 67930, 67933, 67934, 67939, 67945, 67949, 67957, 67963, 67980, 67983, 67988, 67995, 67996, 68008, 68009, 68012, 68024, 68031, 68037, 68047, 68051, 68065, 68066, 68070, 68092, 68101, 68102, 68111, 68116, 68143, 68145, 68160, 68162, 68168, 68171, 68175, 68177, 68193, 68194, 68198, 68199, 68210, 68212, 68217, 68224, 68229, 68237, 68242, 68247, 68250, 68255, 68262, 68274, 68280, 68281, 68288, 68290, 68302, 68306, 68312, 68314, 68326, 68327, 68329, 68331, 68335, 68337, 68338, 68344, 68359, 68361, 68369, 68371, 68376, 68380, 68381, 68382, 68386, 68388, 68403, 68407, 68421, 68433, 68451, 68458, 68464, 68465, 68469, 68474, 68479, 68503, 68507, 68514, 68518, 68525, 68529, 68536, 68541, 68545, 68550, 68553, 68574, 68581, 68588, 68599, 68601, 68606, 68621, 68629, 68634, 68638, 68639, 68657, 68660, 68661, 68671, 68679, 68690, 68692, 68693, 68695, 68704, 68705, 68720, 68730, 68737, 68739, 68750, 68752, 68755, 68760, 68783, 68785, 68787, 68788, 68790, 68791, 68795, 68802, 68803, 68806, 68807, 68811, 68832, 68843, 68848, 68856, 68859, 68864, 68870, 68872, 68880, 68887, 68892, 68896, 68898, 68900, 68906, 68920, 68924, 68937, 68948, 68956, 68957, 68960, 68961, 68963, 68972, 68979, 68999, 69027, 69045, 69048, 69060, 69063, 69065, 69073, 69097, 69101, 69105, 69111, 69142, 69161, 69164, 69166, 69198, 69202, 69208, 69210, 69215, 69221, 69224, 69240, 69243, 69246, 69251, 69253, 69262, 69271, 69275, 69282, 69290, 69309, 69315, 69318, 69319, 69324, 69332, 69335, 69351, 69354, 69360, 69362, 69373, 69403, 69427, 69432, 69434, 69435, 69438, 69441, 69463, 69464, 69467, 69488, 69500, 69504, 69505, 69518, 69523, 69524, 69529, 69535, 69537, 69549, 69553, 69554, 69561, 69564, 69567, 69581, 69582, 69586, 69597, 69600, 69608, 69609, 69610, 69611, 69637, 69641, 69645, 69654, 69655, 69672, 69675, 69679, 69681, 69685, 69686, 69691, 69695, 69703, 69713, 69720, 69734, 69735, 69738, 69753, 69756, 69757, 69760, 69770, 69790, 69791, 69792, 69822, 69825, 69831, 69835, 69836, 69837, 69848, 69858, 69865, 69867, 69871, 69888, 69891, 69928, 69936, 69943, 69950, 69956, 69957, 69965, 69977, 69980, 69993, 69994).

## Valores Financeiros
*   **Venda de Maior Faturamento:** R$ 6,397.00 (Código: 65793).
*   **Venda de Menor Faturamento:** R$ 30.00 (Código: 68371,69597,69928).

---

## 5. Conclusões e Insights
1.  **Perfil de Venda:** A operação é caracterizada por um alto volume de vendas de ticket baixo/médio, com a presença de "vendas estrela" que elevam a média geral.
2.  **Consistência:** O desvio padrão de R$ 716.09 sugere uma variação considerável, recomendando-se uma análise mais profunda sobre os produtos que compõem as vendas *outliers* para tentar replicar esse comportamento em outros clientes.

---

In [30]:
#-------------------------#
# ETAPA 9 - ENVIAR E-MAIL
#-------------------------#

#----------------------------------#
# NOVA ABA
#----------------------------------#
pyautogui.hotkey('ctrl','t')

#----------------------------------#
# ENTRAR NO GMAIL
#----------------------------------#
pyautogui.write('http://mail.google.com/')
pyautogui.press('enter')
time.sleep(4)

#----------------------------------#
# CLICAR EM ESCREVER E-MAIL
#----------------------------------#
pyautogui.click(x=100, y=182)
time.sleep(3)

#----------------------------------#
# ESCREVER DESTINATÁRIO DO E-MAIL
#----------------------------------#
pyautogui.write('phmcasimiro+automacao@gmail.com')
time.sleep(1)
pyautogui.press('tab')
pyautogui.press('tab')
time.sleep(1)

#----------------------------#
# ESCREVER ASSUNTO DO E-MAIL
#----------------------------#
'''
O pyautogui tem um problema com caracteres especiais da língua portuguesa
Em vez de "escrever" o assunto e o corpo do e-mail usando 'pyautogui.write', copie e cole usando 'pyperclip.copy'
'''

from datetime import datetime
import pyautogui
import pyperclip


# ESCREVER ASSUNTO USANDO PYPERCLIP
pyperclip.copy('Relatório de Venda')
pyautogui.hotkey('ctrl','v')
# PULAR PARA CORPO DO E-MAIL
pyautogui.press('tab')
time.sleep(1)


#----------------------------#
# ESCREVER CORPO DO E-MAIL
#----------------------------#

pyperclip.copy("""
# Relatório de Análise Estatística de Vendas

## 1. Visão Geral da Operação
O conjunto de dados analisado apresenta o desempenho de vendas do período, focado no volume transacional e faturamento por nota fiscal (Código Venda).

*   **Volume Total de Vendas (Únicas):** {ds_1['Código Venda'].nunique()} transações.
*   **Ticket Médio (Média por Venda):** R$ {media_vendas:,.2f}
*   **Mediana das Vendas:** R$ {mediana_vendas:,.2f}

## 2. Tendência Central e Dispersão
A análise das medidas de tendência central revela uma **Assimetria Positiva (à Direita)** no faturamento.

*   **Moda:** R$ {moda_vendas[0]:,.2f}
*   **Desvio Padrão:** R$ {desvio_padrao_vendas:,.2f}
*   **Comportamento da Distribuição:** O fato da Média (R$ {media_vendas:,.2f}) ser superior à Mediana (R$ {mediana_vendas:,.2f}) confirma que o faturamento é impulsionado por um grupo seleto de vendas de alto valor, enquanto a maioria das transações se concentra em patamares menores.

## 3. Análise do Boxplot (Distribuição de Frequência)
A leitura visual do diagrama de caixa e do histograma permite identificar:

*   **Primeiro Quartil (Q1):** R$ 262.00 (25% das vendas estão abaixo deste valor).
*   **Terceiro Quartil (Q3):** R$ 1,042.50 (75% das vendas estão abaixo deste valor).
*   **Intervalo Interquartil:** A concentração de 50% das vendas ocorre em uma faixa estreita, indicando uma padronização no consumo da maioria dos clientes.
*   **Outliers:** Identificamos vendas excepcionais fora das hastes (whiskers), que representam oportunidades de grandes contas ou compras fora do padrão usual de consumo.

## 4. Conclusões e Insights
1.  **Perfil de Venda:** A operação é caracterizada por um alto volume de vendas de ticket baixo/médio, com a presença de "vendas estrela" que elevam a média geral.
2.  **Consistência:** O desvio padrão de R$ {desvio_padrao_vendas:,.2f} sugere uma variação considerável, recomendando-se uma análise mais profunda sobre os produtos que compõem as vendas *outliers* para tentar replicar esse comportamento em outros clientes.

---

""")

pyautogui.hotkey('ctrl','v')
time.sleep(10) # Aguardar 10 segundos após o enter

pyautogui.click(x=835, y=679) # enviar e-mail